server:
  port: 8083
spring:
  application:
    name: HireLedger
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    static-path-pattern: /**
  web:
    resources:
      static-locations: classpath:/static/
  session:
    store-type: jdbc
  datasource:
    url: jdbc:mysql://localhost:3308/hireledger
    username: root
    password: rootpassword
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.example.hireledger.domain
  type-handlers-package: com.example.hireledger.utils
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30

logging:
  level:
    com.example.hireledger: DEBUG